name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests (Verificación de Calidad)
        # CORRECCIÓN de 'Permission denied'
        run: npx jest

      # DESPLIEGUE CONTINUO (CD)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # Usa los Secrets de GitHub (Docker PAT)
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # PUBLICA LA IMAGEN EN EL REPOSITORIO DE DOCKER HUB (exealva/biblioteca-api-node-final)
          tags: ${{ secrets.DOCKER_USERNAME }}/biblioteca-api-node-final:latest